#the upper range of RNO
max_random_number: 500
#the maximum number of games supported by server
max_game_number: 20
#path to config temp file
path_to_config_file: /opt/tomcat/webapps/game-configuration.yml
#path_to_config_file: D:\game-configuration.yml
#path to config temp file
path_to_logs_file: /opt/tomcat/webapps/slot-simulator.log
#path_to_logs_file: D:\slot-simulator.log
path_to_results_file: /opt/tomcat/webapps/results.json
#path_to_results_file: D:\results.json


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test


server:
  servlet:
    context-path: /slot-simulator
  port: 8080
