#the upper range of RNO
max_random_number: 500
#the maximum number of games supported by server
max_game_number: 20
#path to config temp file
path_to_config_file: D:\game-configuration.yml
#path to config temp file
path_to_logs_file: /home/michal/slot-simulator.log

server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test